services:
  registro_db:
    image: postgres:16
    container_name: registro_db
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: super_segura_123
      POSTGRES_DB: registro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: registro-backend
    restart: no
    ports:
      - "4000:4000"
    depends_on:
      - registro_db
    env_file:
      - .env.production

volumes:
  postgres_data: